---
- name: Creates directory
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ REPO_DIRE_NAME }}"
    - "{{ REPO_DIRE_NAME }}/traefik"
    - "{{ REPO_DIRE_NAME }}/traefik/certs"
- name: copy bash script
  template:
    src: config_nexus.sh
    dest: "{{ REPO_DIRE_NAME }}/config_nexus.sh"
  - name: Copy trafik config file.
    template:
       src: traefik.yml.j2
       dest: "{{ REPO_DIRE_NAME }}/traefik/config.yml"
      
  - name: copy Docker Compose files
    template:
      src: docker-compose.yml.j2
      dest: "{{ REPO_DIRE_NAME }}/docker-compose.yml"
  - name: Run `docker-compose up` again
    docker_compose:
          project_src: "{{ REPO_DIRE_NAME }}"
          build: no
          files:
            - docker-compose.yml
    register: output
      
  - debug:
        var: output
      
  - name: Pause for 2 minutes to run nexus service
    pause:
          minutes: 2
  - name: Execute the script
        command: bash "{{ REPO_DIRE_NAME }}/config_nexus.sh"
